mymomsage=46
mydadsage=48
mygrandpasage=78
mygrandmasage=75
myothergrandmasage=72
mybrotherdavidsage=18
mybrothervachesage=23
mysisterninosage=15
mysisterbarbaresage=24
myage=12
print(myage+5)
print(mymomsage+5)
print(mydadsage+5)
print(mygrandpasage+5)
print(mygrandmasage+5)
print(myothergrandmasage+5)
print(mybrotherdavidsage+5)
print(mybrothervachesage+5)
print(mysisterninosage+5)
print(mysisterbarbaresage+5)